version: '3'

services:
  shopping-fast:
    container_name: shopping-fast-db
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
